import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Head from 'next/head'
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/sidebar/Sidebar";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});



export const metadata: Metadata = {
  title: "Genius",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <html lang="en" className={`${poppins.className}`}>
      {" "}
      <body>
        <Navbar />
        <div className="flex">
          <Sidebar />

          {children}
        </div>
      </body>
    </html>
  );
}
